from __future__ import annotations

TODAY = "2026-06-10"
DIMENSION = "危废管理"

ISSUES = [
    {
        "slug": "label-incomplete",
        "name": "危废标签不规范",
        "aliases": ["危险废物标签缺项", "危废标签信息不全", "危废标签填写不完整", "标签字段缺失", "危废包装标签不规范"],
        "scene": "危废暂存间包装容器张贴标签环节",
        "risk": "high",
        "evidence_count": 17,
        "confidence": 0.88,
        "recurrence_rate": 0.36,
        "rectification_difficulty": "low",
        "law": "law:swl:art77",
        "obligation": "obl:hw:label-management",
        "tech_spec": "spec:gb18597:label",
        "pitfall": "pitfall:class:hw-label-small-problem",
        "manifestation": "现场常见为标签缺少产生日期、危废类别、责任人或二维码等要素,企业容易把它当作轻微格式问题。",
        "evidence_fields": "标签需核对危废名称、类别代码、产生日期、责任人和容器状态。",
        "rectification": "补齐标签字段并建立入库前复核动作,内部标准包含照片样例与 ETO 判定细则。",
        "report_expression": "建议将危废标签完整性纳入暂存间日常巡检,避免标签信息缺失影响后续贮存和转移管理。",
    },
    {
        "slug": "ledger-incomplete",
        "name": "危废台账不完整",
        "aliases": ["危废管理台账缺失", "危废台账漏记", "入库出库台账不全", "危险废物记录不完整", "台账字段不全"],
        "scene": "危废产生、入库、出库和月度汇总环节",
        "risk": "high",
        "evidence_count": 15,
        "confidence": 0.86,
        "recurrence_rate": 0.42,
        "rectification_difficulty": "medium",
        "law": "law:swl:art78",
        "obligation": "obl:hw:ledger-management",
        "tech_spec": "spec:hj1259:ledger",
        "pitfall": "pitfall:class:hw-ledger-afterthought",
        "manifestation": "现场台账常出现产生量、贮存量、转移量前后不一致,或月末集中补录导致溯源断点。",
        "evidence_fields": "台账需核对产生日期、废物类别、重量、去向、经办人和联单编号。",
        "rectification": "建立按批次及时登记和月度交叉复核机制,内部标准保留错漏类型与复核样例。",
        "report_expression": "建议按产生、贮存、转移三个节点保持台账连续记录,降低后续监管核对时的解释风险。",
    },
    {
        "slug": "storage-partition",
        "name": "危废暂存间分区/分类贮存不规范",
        "aliases": ["危废混放", "危废暂存间未分区", "分类贮存不清", "危废分区标识不明确", "不相容危废混存"],
        "scene": "危废暂存间分类分区与容器摆放环节",
        "risk": "high",
        "evidence_count": 13,
        "confidence": 0.84,
        "recurrence_rate": 0.31,
        "rectification_difficulty": "medium",
        "law": "law:swl:art81",
        "obligation": "obl:hw:storage-partition",
        "tech_spec": "spec:gb18597:storage",
        "pitfall": "pitfall:class:hw-storage-space",
        "manifestation": "现场常见不同类别危废共用区域堆放,分区线、标识牌与实际容器位置不匹配。",
        "evidence_fields": "需核对分区标识、容器摆放、危废类别、相容性和防渗防泄漏设施。",
        "rectification": "按类别重划分区并设置清晰标识,内部标准包含不相容风险判断和整改优先级。",
        "report_expression": "建议优化危废暂存间分区管理,保持标识、容器和台账记录一致。",
    },
    {
        "slug": "warning-sign-missing",
        "name": "危废识别标志/警示标识设置不规范",
        "aliases": ["危废警示标识缺失", "识别标志不规范", "暂存间标识不清", "危险废物标志牌缺失", "标识设置位置不当"],
        "scene": "危废暂存间入口、分区和容器警示标识设置环节",
        "risk": "medium",
        "evidence_count": 11,
        "confidence": 0.82,
        "recurrence_rate": 0.28,
        "rectification_difficulty": "low",
        "law": "law:swl:art77",
        "obligation": "obl:hw:warning-sign",
        "tech_spec": "spec:gb15562:sign",
        "pitfall": "pitfall:class:hw-sign-decoration",
        "manifestation": "现场常见入口无警示牌、标志尺寸不规范或标识被遮挡,企业误以为只要内部人员知道即可。",
        "evidence_fields": "需核对标识位置、尺寸、文字图形、可见性和对应危废类别。",
        "rectification": "补齐入口与分区标志并定期检查可见性,内部标准保留标志样式判断表。",
        "report_expression": "建议完善危废识别标志与警示标识,提高现场管理可识别性。",
    },
    {
        "slug": "transfer-record-mismatch",
        "name": "危废转移、入库、出库记录不一致",
        "aliases": ["危废转移联单与台账不一致", "入库出库记录不一致", "危废转移记录不匹配", "联单台账不符", "危废数量前后不一致"],
        "scene": "危废出入库、转移联单和台账核对环节",
        "risk": "high",
        "evidence_count": 14,
        "confidence": 0.85,
        "recurrence_rate": 0.33,
        "rectification_difficulty": "high",
        "law": "law:swl:art82",
        "obligation": "obl:hw:transfer-record",
        "tech_spec": "spec:hj1259:transfer",
        "pitfall": "pitfall:class:hw-transfer-lag",
        "manifestation": "现场常见联单、出库记录和台账重量或日期不一致,跨月补录后更难追溯。",
        "evidence_fields": "需核对联单编号、转移日期、重量、去向单位、出入库记录和经办人。",
        "rectification": "建立转移前后双人核对和异常差异说明,内部标准包含数量差异处理规则。",
        "report_expression": "建议加强危废转移、入库、出库记录一致性复核,避免形成追溯断点。",
    },
]

LAW_META = {
    "law:swl:art77": ("固体废物污染环境防治法", "第七十七条", "危险废物识别标志与管理要求摘要", "tencent-lke://law/swl/art77"),
    "law:swl:art78": ("固体废物污染环境防治法", "第七十八条", "危险废物管理计划和台账要求摘要", "tencent-lke://law/swl/art78"),
    "law:swl:art81": ("固体废物污染环境防治法", "第八十一条", "危险废物贮存和分类管理要求摘要", "tencent-lke://law/swl/art81"),
    "law:swl:art82": ("固体废物污染环境防治法", "第八十二条", "危险废物转移管理要求摘要", "tencent-lke://law/swl/art82"),
}

TECH_SPECS = {
    "spec:gb18597:label": ("GB 18597 危险废物贮存污染控制标准·标签管理", "危险废物包装标签和贮存管理要求"),
    "spec:gb18597:storage": ("GB 18597 危险废物贮存污染控制标准·贮存分区", "危险废物分类贮存和污染控制要求"),
    "spec:gb15562:sign": ("GB 15562 环境保护图形标志·固体废物贮存处置场", "固体废物贮存设施识别和警示标志要求"),
    "spec:hj1259:ledger": ("HJ 1259 危险废物管理计划和管理台账制定技术导则·台账", "危险废物管理台账记录要求"),
    "spec:hj1259:transfer": ("HJ 1259 危险废物管理计划和管理台账制定技术导则·转移记录", "危险废物转移和台账一致性要求"),
}

EVIDENCE_CATEGORIES = [
    ("evidence:category:site-photo", "现场照片"),
    ("evidence:category:ledger-record", "台账记录"),
    ("evidence:category:label-photo", "标签照片"),
    ("evidence:category:transfer-manifest", "转移联单"),
]

PRIVATE_TYPES = [
    ("evidence_judgment_standard", "证据判断标准", "内部 ETO 判定细则已建立"),
    ("rectification_template", "整改模板", "内部整改闭环模板已建立"),
    ("report_expression", "报告表达模板", "内部报告表达规则已建立"),
]
